language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  if ([ "$TRAVIS_BRANCH" == "next" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    eval 'npm run semantic-release';
  fi
