language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  skip_cleanup: true
  provider: script
  script: npm run semantic-release
  on:
    branch: next
